Revert syn upgrade since it broke a test
Test `kani/Generator/rustc-generator-tests/yield-in-box.rs` fails with:

```
error[E0433]: failed to resolve: maybe a missing crate `core`?
  --> yield-in-box.rs:25:22
   |
25 |             let _t = box (&x, yield 0, &y);
   |                      ^^^ maybe a missing crate `core`?
```